// Single source of truth for which Réalisations actually have their derivatives
// on disk. Both /realisations and the homepage teaser read from here so they can
// never disagree about how many chantiers are published.
//
// Derivatives are generated by ./scripts/convert-realisations.sh — see docs/adr/0003.

import fs from "node:fs";
import path from "node:path";
import { realisations } from "./realisations.js";

const photos = import.meta.glob<{ default: ImageMetadata }>(
  "/src/assets/realisations/**/*.jpg",
  { eager: true },
);

export const photo = (slug: string, file: string): ImageMetadata | undefined =>
  photos[`/src/assets/realisations/${slug}/${file}.jpg`]?.default;

export const videoExists = (slug: string, file: string): boolean =>
  fs.existsSync(path.join(process.cwd(), "public", "realisations", slug, `${file}.mp4`));

const hasAsset = (slug: string, m: any): boolean => {
  if (m.type === "video") return videoExists(slug, m.file);
  if (m.type === "pair") return !!photo(slug, m.avant) && !!photo(slug, m.apres);
  return !!photo(slug, m.file);
};

// A Réalisation whose derivatives haven't been generated would render as an
// empty entry. Drop it rather than ship a headline with nothing under it.
export const published = realisations
  .map((r) => ({ ...r, media: r.media.filter((m) => hasAsset(r.slug, m)) }))
  .filter((r) => r.media.length > 0);

export const communes = [...new Set(published.map((r) => r.commune))];

for (const r of realisations) {
  const kept = published.find((p) => p.slug === r.slug);
  if (!kept) {
    console.warn(`[realisations] "${r.slug}" has no available media — omitted from the site.`);
  } else if (kept.media.length < r.media.length) {
    console.warn(
      `[realisations] "${r.slug}": ${r.media.length - kept.media.length} media item(s) missing.`,
    );
  }
}
